"""empty message

Revision ID: 73736568b3eb
Revises: 36cf49293536
Create Date: 2019-03-08 21:35:10.808962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73736568b3eb'
down_revision = '36cf49293536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_at')
    # ### end Alembic commands ###
